---

- name: Create Jupyter Group
  group:
    name: jupyter
    state: present

# Generate default user password using mkpasswd --method=sha-512
- name: Create Jupyter default user
  user:
    name: jupyter
    # pw = jupyter2021
    password: $6$uuYBChGZ/XRIZu$PybSr9BskTdgiQ//KvwkYfU8Aly73FSRHYkWwaQQCNZrs0n7NzzH59ibyTGfUg0tSUSrpsi4Xqva4eQf5UJ6J1
    state: present
    append: yes
    groups: jupyter, adm, wheel

- name: Create Jupyter Folder
  file:
    path: /etc/jupyterhub
    state: directory
    mode: 0755
    owner: jupyter
    group: jupyter

- name: Configure Jupyterhub
  command:
    cmd: /opt/anaconda3/bin/jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py

- name: Set jupyterhub Admin Users
  lineinfile:
    path: "/etc/jupyterhub/jupyterhub_config.py"
    line: "c.Authenticator.admin_users = {'jupyter'}"
    insertafter: EOF
    create: yes

- name: Set jupyterhub Create Users
  lineinfile:
    path: "/etc/jupyterhub/jupyterhub_config.py"
    line: "c.LocalAuthenticator.create_system_users = True"
    insertafter: EOF
    create: yes

- name: Set jupyterhub base url
  lineinfile:
    path: "/etc/jupyterhub/jupyterhub_config.py"
    line: "c.JupyterHub.bind_url = 'http://0.0.0.0:8000'"
    insertafter: EOF
    create: yes

- name: Set jupyterhub hub url
  lineinfile:
    path: "/etc/jupyterhub/jupyterhub_config.py"
    line: "c.JupyterHub.hub_bind_url = 'http://127.0.0.1:8081'"
    insertafter: EOF
    create: yes

- name: Set jupyterhub hub IP
  lineinfile:
    path: "/etc/jupyterhub/jupyterhub_config.py"
    line: "c.JupyterHub.hub_ip = '0.0.0.0'"
    insertafter: EOF
    create: yes

- name: Set jupyterhub Spawner class
  lineinfile:
    path: "/etc/jupyterhub/jupyterhub_config.py"
    line: "c.JupyterHub.spawner_class = 'sudospawner.SudoSpawner'"
    insertafter: EOF
    create: yes

- name: Copy JupyterHub init script
  copy:
    src: jupyterhub.service
    dest: /etc/systemd/system/jupyterhub.service
    mode: 755
    owner: root
    group: wheel

- name: Start Jupyterhub Service
  systemd:
    daemon-reload: yes
    name: jupyterhub
    state: started
#  service:
#    name: jupyterhub
#    enabled: yes
#    state: started