---

- name: Install OS packages and dependencies
  include_tasks: 'os_packages.yml'

- name: Install R
  include_tasks: 'install_r.yml'

- name: Install RStudio
  include_tasks: 'install_rstudio.yml'

- name: Install Conda
  include_tasks: 'install_conda.yml'

- name: Configure JupyterHub users and uses
  include_tasks: 'jupyter_cfg.yml'